name: MacOS

on:
  push:
    paths:
      - '.github/workflows/macos.yml'
      - 'CMakeLists.txt'
      - 'src/**'
      - 'test/**'
      - 'modules/**'
      - '3rdparty/**'
  pull_request:
    paths:
      - '.github/workflows/macos.yml'
      - 'CMakeLists.txt'
      - 'src/**'
      - 'test/**'
      - 'modules/**'
      - '3rdparty/**'
  release:
    types: published

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        config: [Release, Debug]
        # Can't build with later than macos-13 yet, newton dynamics 3.14 can't handle it.
        image: [macos-13]

    runs-on: ${{ matrix.image }}

    env:
      CC:  ${{ matrix.compiler == 'gcc' && 'gcc' || 'clang'   }}
      CXX: ${{ matrix.compiler == 'gcc' && 'g++' || 'clang++' }}
      CMAKE_C_COMPILER_LAUNCHER: ccache
      CMAKE_CXX_COMPILER_LAUNCHER: ccache

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: recursive

    - uses: hendrikmuhs/ccache-action@v1
      with:
        key: macos-${{ matrix.image }}-${{ matrix.compiler }}-${{ matrix.config }}

    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@v1.1

    - name: Configure
      shell: bash
      run: |
        cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_LINK_WHAT_YOU_USE=TRUE

    - name: Compile Dependencies
      shell: bash
      run: |
        cmake --build build --parallel --config ${{ matrix.config }} --target compile-osp-magnum-deps compile-test-deps

    - name: Compile OSP-Magnum
      shell: bash
      run: |
        cmake --build build --parallel --config ${{ matrix.config }} --target osp-magnum

    - name: Compile Unit Tests
      shell: bash
      run: |
        cmake --build build --parallel --config ${{ matrix.config }} --target compile-tests

    # TODO: Why doesn't the "test" target execute tests?
    - name: Run Unit Tests
      shell: bash
      run: |
        ctest --schedule-random --progress --output-on-failure --parallel --no-tests=error --build-config ${{ matrix.config }} --test-dir build

    - uses: actions/upload-artifact@v4
      with:
        name: OSP-macOS-${{ matrix.image}}-${{ matrix.config }}-${{ matrix.compiler }}
        path: build/${{ matrix.config }}
